# Generated by Django 4.2.4 on 2023-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=600)),
                ('price', models.PositiveIntegerField()),
                ('Image', models.ImageField(upload_to='ClothProducts')),
            ],
        ),
    ]
